import Head from "next/head";

import Hero from "@/components/Hero/Hero";
import VideoPlayer from "@/components/VideoPlayer/VideoPlayer";
import Card from "@/components/Card/Card";
import { useRef } from "react";

export default function Home({ data }) {
  const videoRef = useRef(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <div className="w-full px-14 relative">
          <VideoPlayer videoRef={videoRef} />
          <div className="flex flex-col w-full -mt-[40rem]">
            {data.texts.map((currData, index) => {
              return (
                <Card
                  currData={currData}
                  currKey={index}
                  key={index}
                  videoRef={videoRef}
                />
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    `https://mocki.io/v1/ee762599-31ae-4a3d-a6c7-d596525945e1`
  );
  const data = await res.json();

  return { props: { data } };
}
